### SHOPEE ADS
GET http://localhost:1337/api/v1/shopee-seller/product-ads
Content-Type: application/json

{
    "startDefault": "1747414800",
    "endDefault": "1748019599"
}

### SHOPEE ADS DAILY
GET http://localhost:1337/api/v1/shopee-seller/product-ads-daily
Content-Type: application/json


### USER INFO
GET http://localhost:1337/api/v1/shopee-seller/user-profile
Content-Type: application/json

### PRODUCT STOCK
GET http://localhost:1337/api/v1/shopee-seller/product-stock
Content-Type: application/json

### PRODUCT KEYWORD
GET http://localhost:1337/api/v1/shopee-seller/product-keyword
Content-Type: application/json

{
    "startDefault": "1747414800",
    "endDefault": "1748019599"
}

### PRODUCT PERFORMANCE
GET http://localhost:1337/api/v1/shopee-seller/product-performance
Content-Type: application/json

{
    "startDefault": "1747328400",
    "endDefault": "1747933199"
}

### AUTO LOGIN
GET http://localhost:1337/api/v1/shopee-seller/login
Content-Type: application/json