### SHOPEE ADS
GET http://localhost:1337/api/v1/shopee-seller/product-ads
Content-Type: application/json

{
    "startDefault": "1744909200",
    "endDefault": "1744995599"
}

### SHOPEE ADS DAILY
GET http://localhost:1337/api/v1/shopee-seller/product-ads-daily
Content-Type: application/json


### USER INFO
GET http://localhost:1337/api/v1/shopee-seller/user-profile
Content-Type: application/json

### PRODUCT STOCK
GET http://localhost:1337/api/v1/shopee-seller/product-stock
Content-Type: application/json

### PRODUCT KEYWORD
GET http://localhost:1337/api/v1/shopee-seller/product-keyword
Content-Type: application/json

{
    "startDefault": "1746464400",
    "endDefault": "1746550799",
    "campaignId": "314012238"
}

### PRODUCT PERFORMANCE
GET http://localhost:1337/api/v1/shopee-seller/product-performance
Content-Type: application/json

{
    "startDefault": "1744909200",
    "endDefault": "1744995599"
}

### AUTO LOGIN
GET http://localhost:1337/api/v1/shopee-seller/login
Content-Type: application/json