###
GET http://localhost:1337/api/v1/instagram/rapid/getDataUser
Content-Type: application/json

{
    "kategori" : "disparbud"
}

###
GET http://localhost:1337/api/v1/instagram/rapid/getDataPost
Content-Type: application/json

{
    "kategori" : "disparbud"
}